version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: ibrahimawe/reverseproxy
  backend_user:
    build:
      context: ../../user
    image: ibrahimawe/user
  backend_feed:
    build:
      context: ../../feed
    image: ibrahimawe/feed
  frontend:
    build:
      context: ../../udagram-frontend  
    image: ibrahimawe/udagram-frontend
